### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by palainp** [mirleft/ocaml-tls#447] opened 2022-06-09 09:12 UTC
Tls seems to be unhappy with the certificate at `https://torproject.org/`. The debug logs are really verbose and I'm not sure what to check in it. To reproduce:
```
git clone https://github.com/mirage/mirage-skeleton.git
cd mirage-skeleton/device-usage/http-fetch
mirage configure -t unix && make depend && dune build
./dist/http-fetch --uri https://mirage.io # is ok
./dist/http-fetch --uri https://torproject.org # is ko, failing with Fatal error: exception Failure("connect: authentication failure: invalid certificate chain")
```
I spotted a difference: the torproject certificate have TLS_AES_256_GCM_SHA384 and have a 256 bits key, whereas mirage.io have TLS_AES_128_GCM_SHA256 and have a 128 bits key, both TLS 1.3. This could be related but I'm unsure how to test that.

**Comment by hannesm** [comment] 2022-06-09 10:36
Thanks for your report. The "authentication failure: invalid certificate chain" boils down to something is different in respect to the certificate chain.

But that is strange, since according to sslabs and local tests, torproject provides the same CA chain as mirage.io.. DST Root CA X3; ISRG Root X1; Let's Encrypt R3. Would you mind to figure out which ca-certs-nss opam package you have installed?

**Comment by palainp** [comment] 2022-06-09 13:10
None was installed on my system and the one chosen by dune is version 3.77.

**Comment by palainp** [comment] 2022-06-09 13:27
And thanks for the pointers.

I also tried to pin directly to mirage/ca-certs-nss but no more luck. I'll continue the investigations.

**Comment by hannesm** [comment] 2022-06-09 13:46
I guess printing the certificates that you received and look whether there's a hole in the chain or they are in reverse order or something along these lines would be useful.

**Comment by palainp** [comment] 2022-06-09 16:53
A difference between the two logs is that for both `torproject.org` and `mirage.io` can see a `CHANGE_CIPHER_SPEC` without any prob, and a second one only for `torproject.org`, just before the exception:
```
...
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (record-in
                   (((content_type CHANGE_CIPHER_SPEC) (version TLS_1_2))
                    "\001"))
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (frame-in (CHANGE_CIPHER_SPEC "\001"))
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (record-in
                   (((content_type APPLICATION_DATA) (version TLS_1_2))
                    "W\127\149\172\2305@k\198q\218\169\255 z\193p\251\025\188\178\146\240"))
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (frame-in (HANDSHAKE "\b\000\000\002\000\000"))
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (handshake-in (EncryptedExtensions ()))
2022-06-09 18:19:18 +02:00: DBG [tls.tracing] (record-in
                   (((content_type APPLICATION_DATA) (version TLS_1_2))
...
```
The pretty printed certificate does contains references `auto-ca.torproject.org`. I'll try to export this new certificate to inspect its content.

**Comment by hannesm** [comment] 2022-06-21 12:50
I looked into this a bit more, using the following patch to x509:
```diff
commit d7b2232a3eb94876b81bb3ea523f554b6240c01f (HEAD -> debug)
Author: Hannes Mehnert <hannes@mehnert.org>
Date:   Tue Jun 21 14:27:38 2022 +0200

    print chains

diff --git a/lib/validation.ml b/lib/validation.ml
index 9a768c0..256f989 100644
--- a/lib/validation.ml
+++ b/lib/validation.ml
@@ -445,6 +445,11 @@ let verify_chain_of_trust ?ip ~host ~time ?revoked ?(allowed_hashes = sha2) ~anc
     let paths = build_paths server certs
     and anchors = List.filter (validate_time now) anchors
     in
+    Log.info (fun m -> m "paths %d server certificate\n%s\n\nchain\n%a"
+                 (List.length paths)
+                 (Cstruct.to_string (Certificate.encode_pem server))
+                 Fmt.(list ~sep:(any "\n\n") string)
+                 (List.map (fun c -> Cstruct.to_string (Certificate.encode_pem c)) certs));
     (* exists there one which is good? *)
     any_m `InvalidChain (verify_single_chain now ?revoked allowed_hashes anchors) paths
 
```

When connecting to https://torpoject.org, only a single X.509 certificate is returned:
```
-----BEGIN CERTIFICATE-----
MIIFVTCCBD2gAwIBAgICBzYwDQYJKoZIhvcNAQELBQAwgaAxDzANBgNVBAgTBkts
YXRjaDERMA8GA1UEBxMIQWwgS2hhbGkxFzAVBgNVBAoTDnRvcnByb2plY3Qub3Jn
MRAwDgYDVQQLEwdhdXRvLUNBMR8wHQYDVQQDExZhdXRvLWNhLnRvcnByb2plY3Qu
b3JnMS4wLAYJKoZIhvcNAQkBFh90b3Jwcm9qZWN0LWFkbWluQHRvcnByb2plY3Qu
b3JnMB4XDTIyMDYxNTAwMDAwMloXDTIzMDYxNTAwMDAwMlowgagxDzANBgNVBAgT
BktsYXRjaDERMA8GA1UEBxMIQWwgS2hhbGkxFzAVBgNVBAoTDnRvcnByb2plY3Qu
b3JnMRAwDgYDVQQLEwdhdXRvLUNBMSIwIAYDVQQDExl3ZWItZnNuLTAxLnRvcnBy
b2plY3Qub3JnMTMwMQYJKoZIhvcNAQkBFiRob3N0bWFzdGVyQHdlYi1mc24tMDEu
dG9ycHJvamVjdC5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDF
AH2iawUG5aTQ4vtVI/heYWneYvb3V0R/YJTemDHZqq++ZJt1JKnWiBVl2HUAOZKT
yAOo8ZH9+sqnW1gtPMXrUGoq2Zg8vm8mHMj5ANQyHSjQDXeupA1f3mfbPRbWUJGP
6cDUsVWafL7HwRiENg9KtaPFpcJD8kgHRi6SFgFu86fCMnO8Z7MIjyvqcN1Ng7BS
W1pvfG4ZAgcBCgH3jz9dd4x2gWzp57JQ246D6aJ9WKpR4x53I8ofFKM2p369WWYR
g+nYlRezzQ92lSLdaXj2SyhLO1e8h261v8XHmMn34IUaB/XDwnH40XxZ6q1hfKQk
UU8amoRdqYGkrrJVzeyLAgMBAAGjggGNMIIBiTAJBgNVHRMEAjAAMBEGCWCGSAGG
+EIBAQQEAwIGQDAqBglghkgBhvhCAQ0EHRYbdG9ycHJvamVjdC5vcmcgYXV0by1D
QSBjZXJ0MB0GA1UdDgQWBBQWXUpEevVXcTCqocUE211XTag8STCB1QYDVR0jBIHN
MIHKgBTo5w8b8+Mavi2Srk6R0tx595rGbqGBpqSBozCBoDEPMA0GA1UECBMGS2xh
dGNoMREwDwYDVQQHEwhBbCBLaGFsaTEXMBUGA1UEChMOdG9ycHJvamVjdC5vcmcx
EDAOBgNVBAsTB2F1dG8tQ0ExHzAdBgNVBAMTFmF1dG8tY2EudG9ycHJvamVjdC5v
cmcxLjAsBgkqhkiG9w0BCQEWH3RvcnByb2plY3QtYWRtaW5AdG9ycHJvamVjdC5v
cmeCCQDd3v9hxg7AfTATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMCBaAw
JAYDVR0RBB0wG4IZd2ViLWZzbi0wMS50b3Jwcm9qZWN0Lm9yZzANBgkqhkiG9w0B
AQsFAAOCAQEAkdD1E2GHw+OdgdmzbsHxKEgt7u3+IxRADHfqsKDFsUwyOyVybhn6
/x8b9Nw28BNumtmhGELS4U+EyB0qgVMPa8xgi39iYH+FbITeYZQMQ7Z0KQ02+bi5
3ZUV51YPO1IX4QvwwP1mxIFGxXFtN9mx+wGmiLL4MtF4cmLr7yyp8zckAHt05Rt5
Du+KkUuNv01NshzvlI2XBnqMWzs+2SXqjD0u5oCr/tsq7VQFcO2eOmg7dl0yqCSt
YKWiQrxXd4Wvhq70xIJ/hWJtuvEgkIkp6Y6nlY4lB8M/1y/wVChViu2O265pm+E0
Z9xIC8DLQPHcoaN7QWWdd+FxrfZKzKBSww==
-----END CERTIFICATE-----
```

Which, decoded using openssl x509 -text -noout:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1846 (0x736)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: ST = Klatch, L = Al Khali, O = torproject.org, OU = auto-CA, CN = auto-ca.torproject.org, emailAddress = torproject-admin@torproject.org
        Validity
            Not Before: Jun 15 00:00:02 2022 GMT
            Not After : Jun 15 00:00:02 2023 GMT
        Subject: ST = Klatch, L = Al Khali, O = torproject.org, OU = auto-CA, CN = web-fsn-01.torproject.org, emailAddress = hostmaster@web-fsn-01.torproject.org
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:c5:00:7d:a2:6b:05:06:e5:a4:d0:e2:fb:55:23:
                    f8:5e:61:69:de:62:f6:f7:57:44:7f:60:94:de:98:
                    31:d9:aa:af:be:64:9b:75:24:a9:d6:88:15:65:d8:
                    75:00:39:92:93:c8:03:a8:f1:91:fd:fa:ca:a7:5b:
                    58:2d:3c:c5:eb:50:6a:2a:d9:98:3c:be:6f:26:1c:
                    c8:f9:00:d4:32:1d:28:d0:0d:77:ae:a4:0d:5f:de:
                    67:db:3d:16:d6:50:91:8f:e9:c0:d4:b1:55:9a:7c:
                    be:c7:c1:18:84:36:0f:4a:b5:a3:c5:a5:c2:43:f2:
                    48:07:46:2e:92:16:01:6e:f3:a7:c2:32:73:bc:67:
                    b3:08:8f:2b:ea:70:dd:4d:83:b0:52:5b:5a:6f:7c:
                    6e:19:02:07:01:0a:01:f7:8f:3f:5d:77:8c:76:81:
                    6c:e9:e7:b2:50:db:8e:83:e9:a2:7d:58:aa:51:e3:
                    1e:77:23:ca:1f:14:a3:36:a7:7e:bd:59:66:11:83:
                    e9:d8:95:17:b3:cd:0f:76:95:22:dd:69:78:f6:4b:
                    28:4b:3b:57:bc:87:6e:b5:bf:c5:c7:98:c9:f7:e0:
                    85:1a:07:f5:c3:c2:71:f8:d1:7c:59:ea:ad:61:7c:
                    a4:24:51:4f:1a:9a:84:5d:a9:81:a4:ae:b2:55:cd:
                    ec:8b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Cert Type: 
                SSL Server
            Netscape Comment: 
                torproject.org auto-CA cert
            X509v3 Subject Key Identifier: 
                16:5D:4A:44:7A:F5:57:71:30:AA:A1:C5:04:DB:5D:57:4D:A8:3C:49
            X509v3 Authority Key Identifier: 
                keyid:E8:E7:0F:1B:F3:E3:1A:BE:2D:92:AE:4E:91:D2:DC:79:F7:9A:C6:6E
                DirName:/ST=Klatch/L=Al Khali/O=torproject.org/OU=auto-CA/CN=auto-ca.torproject.org/emailAddress=torproject-admin@torproject.org
                serial:DD:DE:FF:61:C6:0E:C0:7D

            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:web-fsn-01.torproject.org
    Signature Algorithm: sha256WithRSAEncryption
    ...
```

This is not a certificate backed by a trust anchor.

The reason that the http-fetch unikernel receives this certificate is that it lacks to specify the hostname (server name indication) in the TLS client hello -- you get the same result if you use `openssl s_client -connect 116.202.120.166:443`.

The issue is somewhere in cohttp or conduit (where the Tls.Config.t / Tls.Config.client is constructed (taking an optional `~peer_name`), or where Tls_mirage.client_of_flow is executed (which takes an optional `~host` argument).

I'd propose to figure out whether the information of Url (Uri.host) is available in some context where client_of_flow is called, and provide the `~host` argument as well. Since there's nothing that can be done at the TLS API / layer, I'm closing this issue here.

**Closed by hannesm** 2022-06-21 12:50 UTC

**Comment by palainp** [comment] 2022-06-21 15:57
Many thanks @hannesm! This patch and the PR on conduit will help me elsewhere too :)
